FROM debian:latest

RUN #apt-get update && \
    apt-get install -y \
    vim                     #replace with your editor of choice \
    tmux                    #can replace with screen \
    python \
    ipython \
    openssl                 #required for curl-loader \
    libssl-dev              #required for curl-loader \
    lft \
    hping3 \
    net-tools               #install ifconfig, etc