FROM debian:latest
LABEL version="0.1" description="development container"
MAINTAINER Victor Clark <victor@victorclark.org>

RUN \
    apt-get update && \
    apt-get install -y \
    vim \
    python \
    ipython \
    lft \
    hping3 \
    net-tools